# Generated by Django 4.2.5 on 2023-10-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_ID', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('letter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LabWork',
            fields=[
                ('lab_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_ID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(unique=True)),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.AutoField(primary_key=True, serialize=False)),
                ('class_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('full_name', models.TextField()),
                ('role', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_ID', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_ID', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.labwork')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.labwork')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.user'),
        ),
        migrations.AddField(
            model_name='labwork',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.subject'),
        ),
        migrations.CreateModel(
            name='GuestPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.guest')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.labwork')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.user'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_ID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='back.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherClass',
            fields=[
                ('class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='back.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='back.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='back.subject')),
                ('class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.class')),
            ],
        ),
    ]
