# Generated by Django 4.2.5 on 2023-10-09 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_student_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date published'),
        ),
    ]
