# Generated by Django 4.2.5 on 2023-10-09 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_student_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 15, 47, 26, 978908, tzinfo=datetime.timezone.utc), null=True, verbose_name='date published'),
        ),
    ]
